:set nohlsearch
:set titleold=
:set nohls
:set ignorecase
:set smartcase
:set cindent
:set autoindent
:let loaded_matchparen = 1
:set cinkeys = "0{,0},0),:,!^F,o,O,e"
:filetype plugin on
map <C-k> <C-y><C-y>
map <C-j> <C-e><C-e>
map F zO
vnoremap p <Esc>:let current_reg = @"<CR>gvs<C-R>=current_reg<CR><Esc>

if version >= 600
	set foldenable
	set foldmarker={,}
	set foldmethod=marker
endif

map <C-B> :!php -l %<CR>

autocmd BufReadPost *
\ if line("'\"") > 0 && line("'\"") <= line("$") |
\ exe "normal g`\"" |
\ endif
augroup END

if version >= 500
  let c_comment_strings=1
  if !exists("syntax_on")
    syntax on
  endif
"  highlight Normal guibg=grey90
"  highlight Cursor guibg=Green guifg=NONE
"  highlight lCursor guibg=Cyan guifg=NONE
"  highlight NonText guibg=grey80
"  highlight Constant gui=NONE guibg=grey95
"  highlight Special gui=NONE guibg=grey95
endif

au BufWinLeave * mkview
au BufWinEnter * silent loadview


:set tabstop=4
:set shiftwidth=4
:set expandtab
:set softtabstop=4


filetype plugin on
:au BufRead,BufNewFile *.ejs set filetype=html
:au BufRead,BufNewFile *.twig set filetype=jinja
:au BufRead,BufNewFile *.html.twig set filetype=jinja
:au BufRead,BufNewFile *.jinja set filetype=jinja
:au BufRead,BufNewFile *.node set filetype=javascript
:au BufRead,BufNewFile /opt/local/etc/nginx/* if &ft == '' | setfiletype nginx | endif
:au BufRead,BufNewFile /opt/local/etc/nginx/sites-available/* if &ft == '' | setfiletype nginx | endif
:au BufRead,BufNewFile /opt/local/etc/nginx/sites-enabled/* if &ft == '' | setfiletype nginx | endif

set directory=~/.vim/swp//
